# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,6,7]])


# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[6,7,8]]])
a1.ndim,a2.ndim,a3.ndim,a1.shape,a2.shape,a3.shape,a1.dtype,a1.size

(1, 2, 3, (3,), (2, 3), (1, 3, 3), dtype('int32'), 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim,a1.dtype,a1.size, type(a1)

(1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2

array([[1, 2, 3],
       [4, 6, 7]])

In [5]:
# Attributes of 3-dimensional array
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame(a2,index=['mon','tue'],columns=['first priority','second priority','third priority'])
data

first priority  second priority  third priority
mon               1                2               3
tue               4                6               7

In [7]:
# Create an array of shape (10, 2) with only ones
ar=np.ones((10,2))
ar

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
ar1=np.ones((7,2,3))
ar1

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
ar2=np.random.random(100)
ar2

array([1.25363282e-01, 9.58598409e-01, 2.52001866e-01, 6.08466320e-01,
       7.16539268e-01, 8.14537178e-01, 4.25772567e-01, 7.76365831e-01,
       2.99480554e-01, 3.94843704e-01, 6.26432785e-01, 3.91853185e-01,
       5.41171033e-01, 2.21853917e-01, 3.14529396e-01, 4.46724541e-01,
       2.07110451e-01, 8.05740680e-04, 2.91790417e-01, 7.90146652e-01,
       8.26540868e-01, 3.94719027e-02, 7.08878350e-01, 6.78560771e-01,
       9.57410827e-01, 8.97440743e-01, 7.34501117e-01, 2.77717469e-01,
       2.73577489e-01, 1.78430671e-01, 9.38470704e-01, 1.76745853e-01,
       1.29817198e-01, 6.62988336e-01, 9.93295268e-01, 5.00388821e-01,
       3.20951062e-01, 4.22070510e-01, 9.16864939e-02, 4.82067284e-01,
       3.30502143e-01, 2.61409677e-01, 1.35634387e-01, 4.26950175e-01,
       3.25436796e-01, 2.08075212e-01, 6.24141561e-01, 9.61729453e-01,
       5.31371905e-02, 5.41798084e-01, 8.85531693e-01, 7.91605694e-01,
       9.56790965e-01, 8.80853207e-01, 6.49049156e-01, 3.80741396e-01,
      

In [52]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ran_arry=np.random.randint(0,10,size=(7,2))
ran_arry

array([[0, 8],
       [9, 8],
       [1, 8],
       [4, 0],
       [8, 2],
       [4, 4],
       [7, 3]])

In [57]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ran_arr1=np.random.random((3,5))
ran_arr1

array([[0.11758944, 0.03670551, 0.83283965, 0.934158  , 0.7551701 ],
       [0.32320724, 0.26846271, 0.03874547, 0.59250748, 0.35452295],
       [0.71832313, 0.71639025, 0.26318129, 0.82024676, 0.79221792]])

In [60]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ran_arr2 = np.random.randint(0,10,size=(4,6))
ran_arr2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [76]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
ran_arr3 = np.random.randint(1,10,size=(3,7))
ran_arr3
# and save it to a variable
ran_arr4=np.save('f',ran_arr3)
# Find the unique numbers in the array you just created
unic=np.unique(ran_arr3)
unic

array([1, 2, 3, 4, 6, 7, 8, 9])

In [75]:
# Find the 0'th index of the latest array you created
unic[0]

1

In [77]:
# Get the first 2 rows of latest array you created
ran_arr3[:2]

array([[2, 6, 7, 2, 2, 1, 8],
       [1, 9, 6, 7, 7, 3, 2]])

In [86]:
# Get the first 2 values of the first 2 rows of the latest array
ran_arr3[:2,:2]

array([[2, 6],
       [1, 9]])

In [94]:
# Create a random array of numbers between 0 & 10 and an array of ones
ran_arr5 = np.random.randint(0,10,size=(3,5))
ran_arr5
# both of size (3, 5), save them both to variables
ones2=np.ones((3,5))
ones2,ran_arr5
ff=np.save('f',ones2,ran_arr5)

In [95]:
# Add the two arrays together
ones2+ran_arr5

array([[ 5.,  3.,  1.,  1.,  8.],
       [10.,  2.,  3.,  2.,  3.],
       [ 7.,  1., 10.,  8., 10.]])

In [101]:
# Create another array of ones of shape (5, 3)
ones3=np.ones((5,3))
ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:

# Try add the array of ones and the other most recent array together
add=ones3+ ran_arr5.T
add

array([[ 5., 10.,  7.],
       [ 3.,  2.,  1.],
       [ 1.,  3., 10.],
       [ 1.,  2.,  8.],
       [ 8.,  3., 10.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [105]:
# Create another array of ones of shape (3, 5)
ones4=np.ones((3,5))
ones4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
# Subtract the new array of ones from the other most recent array
sub=add+ones4.T
sub

array([[ 6., 11.,  8.],
       [ 4.,  3.,  2.],
       [ 2.,  4., 11.],
       [ 2.,  3.,  9.],
       [ 9.,  4., 11.]])

In [112]:
# Multiply the ones array with the latest array
mult=ones4*sub.T
mult

array([[ 6.,  4.,  2.,  2.,  9.],
       [11.,  3.,  4.,  3.,  4.],
       [ 8.,  2., 11.,  9., 11.]])

In [116]:
# Take the latest array to the power of 2 using '**'
squr = mult**2
squr

array([[ 36.,  16.,   4.,   4.,  81.],
       [121.,   9.,  16.,   9.,  16.],
       [ 64.,   4., 121.,  81., 121.]])

In [119]:
# Do the same thing with np.square()
squr1=np.square(squr)
squr1

array([[ 1296.,   256.,    16.,    16.,  6561.],
       [14641.,    81.,   256.,    81.,   256.],
       [ 4096.,    16., 14641.,  6561., 14641.]])

In [120]:
# Find the mean of the latest array using np.mean()
np.mean(squr1)

4227.666666666667

In [121]:
# Find the maximum of the latest array using np.max()
np.max(squr1)

14641.0

In [122]:
# Find the minimum of the latest array using np.min()
np.min(squr1)

16.0

In [123]:
# Find the standard deviation of the latest array
np.std(squr1)

5655.321584332956

In [124]:
# Find the variance of the latest array
np.var(squr1)

31982662.222222216

In [127]:
# Reshape the latest array to (3, 5, 1)
res=squr1.reshape(3,5,1)

In [128]:
# Transpose the latest array
res.T

array([[[ 1296., 14641.,  4096.],
        [  256.,    81.,    16.],
        [   16.,   256., 14641.],
        [   16.,    81.,  6561.],
        [ 6561.,   256., 14641.]]])

What does the transpose do?

In [129]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ran_arr6 = np.random.randint(0,10,size=(3,3))
ran_arr7 = np.random.randint(0,10,size=(3,2))

In [130]:
# Perform a dot product on the two newest arrays you created
ran_arr6.dot(ran_arr7)

array([[ 40, 143],
       [ 50, 126],
       [ 46, 125]])

In [131]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ran_arr61 = np.random.randint(0,10,size=(4,3))
ran_arr62 = np.random.randint(0,10,size=(4,3))

In [133]:
# Perform a dot product on the two newest arrays you created
ran_arr61.dot(ran_arr62.T)

array([[ 91,  78,  74,  12],
       [106,  54,  94,   6],
       [ 24,  30,  28,   9],
       [ 31,  36,  56,  18]])

It doesn't work. How would you fix it?

In [134]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ran_arr61.dot(ran_arr62.T)

array([[ 91,  78,  74,  12],
       [106,  54,  94,   6],
       [ 24,  30,  28,   9],
       [ 31,  36,  56,  18]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [137]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ff=np.save('f',ones2,ran_arr5)
ff

In [139]:
# Compare the two arrays with '>'
ran_arr61>ran_arr62

array([[False,  True, False],
       [ True,  True, False],
       [False, False, False],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [140]:
# Compare the two arrays with '>='
ran_arr61>=ran_arr62

array([[False,  True,  True],
       [ True,  True, False],
       [False,  True, False],
       [ True,  True,  True]])

In [146]:
# Find which elements of the first array are greater than 7
ran_arr61[ran_arr61>7]

array([9, 8])

In [145]:
# Which parts of each array are equal? (try using '==')
ran_arr61[ran_arr61==7]

array([7])

In [150]:
# Sort one of the arrays you just created in ascending order
np.sort(ran_arr1)

array([[0.03670551, 0.11758944, 0.7551701 , 0.83283965, 0.934158  ],
       [0.03874547, 0.26846271, 0.32320724, 0.35452295, 0.59250748],
       [0.26318129, 0.71639025, 0.71832313, 0.79221792, 0.82024676]])

In [155]:
# Sort the indexes of one of the arrays you just created
np.argsort(ran_arr6)

array([[2, 0, 1],
       [0, 2, 1],
       [0, 2, 1]], dtype=int64)

In [156]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ran_arr6)

0

In [157]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ran_arr1)

1

In [158]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ran_arr6 ,axis=1)

array([0, 1, 1], dtype=int64)

In [159]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(ran_arr6,axis=0)

array([0, 0, 1], dtype=int64)

In [164]:
# Create an array of normally distributed random numbers
np.random.randn(10,2)

array([[-0.34320124,  0.45767645],
       [ 0.06965266,  0.98350431],
       [ 0.47362739,  0.05435058],
       [ 2.2757613 ,  0.40622669],
       [-0.4319422 ,  1.85996701],
       [ 1.20041155,  1.81608779],
       [-0.11093194,  0.97630913],
       [-1.45284946,  0.78400641],
       [-0.15772396, -1.35505796],
       [ 1.0326004 , -1.81013132]])

In [166]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(2,5,9)

array([2.   , 2.375, 2.75 , 3.125, 3.5  , 3.875, 4.25 , 4.625, 5.   ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.